### PR TITLE
Temporal Reversal Decision Improvement

### LINKED ISSUE #1367: Temporal Reversal does not have choose for me or decision text
**Describe the bug**
The Temporal Reversal card's effect should have a choose for me button. It also could have a decision title, right now it does not.

**What does it affect**
Card(s):Temporal Reversal
Deck(s):FSC environment

### PR DESCRIPTION
**Pull request by wrhyme29**
Closes #1367

### CODE REVIEW

File: CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/TemporalReversalCardController.cs [hunk 1]
```diff
@@ -64,5 +68,32 @@ public override void AddTriggers()
...
         }
 
+        public override CustomDecisionText GetCustomDecisionText(IDecision decision)
+        {
+
+            return new CustomDecisionText($"Select the {GetAdjective(deckAdjectiveCount)} deck to return a card to the top of.", $"Select the { GetAdjective(deckAdjectiveCount) } deck to return a card to the top of.", $"Vote for the {GetAdjective(deckAdjectiveCount)} deck to return a card to the top of.", "return a card to deck");
+
+        }
+
+        private string GetAdjective(int deckAdjectiveCount)
```
Comment (MigrantP) [inline CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/TemporalReversalCardController.cs:78]: We have an extension method for this: int.ToOrdinalString()

Comment (wrhyme29) [reply CauldronMods/Controller/Environments/FSCContinuanceWanderer/Cards/TemporalReversalCardController.cs:78]: Ah I was looking through the extension methods and I didn't see that - thank you! I'll adjust it.

**Review by LNBertolini — APPROVED** [review]
