### PR TITLE
Lady of the Wood Fall reduce damage trigger order

### LINKED ISSUE #1309: Lady of the Wood and Fall with Lightning Damage not reducing damage on Sonic Mine
**Describe the bug**
The Season Fall should make damaged targets do -1 damage, but that isn't working on Sonic mine, who I had previously reduced its damage from Crickets power.

**What does it affect**
Card(s): Fall, Sonic Mine
Deck(s): Lady of the Wood, Ambuscade, Cricket

**To Reproduce**
1. Use this setup
2. Play these cards to setup
3. Play the problem card

**Expected behavior**
I expected damaging the Sonic Mine with Lightning would reduce it's damage by -1, as stated on the card Fall.   The Sonic Mine was already at 1hp, so when it was hit with 1 lightning from Lady of the wood it destroyed the Mine, thus setting off it's ability.  The SOnic mine was already doing -1 from Crickets main power, but the -1 from Lady of the Wood was not shown, so the Mine still did 1 damage.  

**Screenshots**

**Logs**
If your game froze or you had a soft lock, please attach the output_log found C:\Users\<YourUsernameHere>\AppData\LocalLow\Handelabra Games Inc_\Sentinels

**Additional context**

### PR DESCRIPTION
**Pull request by cdallasanta**
Copied from Nitrogen Rounds

Closes #1309

### CODE REVIEW

File: CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/FallCardController.cs [hunk 1]
```diff
@@ -14,31 +14,26 @@ public override void AddTriggers()
...
+					ReduceDamageDealtByThatTargetUntilTheStartOfYourNextTurnResponse(damage, 1), requireDamageToBeDealt: true
+				), new TriggerType[]
 			{
 				TriggerType.ReduceDamage
-			}, TriggerTiming.After);
+			}, TriggerTiming.Before);
 		}
-
-		private IEnumerator ReduceDamageResponse(DealDamageAction dd)
+		protected IEnumerator AddStatusEffectResponseToDamage(DealDamageAction dd, Func<DealDamageAction, IEnumerator> statusEffectResponse, bool requireDamageToBeDealt = false)
```
Comment (cdallasanta) [inline CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/FallCardController.cs:25]: Since this is a protected method, and it's only called once with "requireDamageToBeDealt" as true, this method could be simplified by removing it, but I think it makes the method more clearly match the text on the card (plus, I just copied it from Nitrogen Rounds, and it has the same redundancy).

**Comment by LNBertolini** [comment]
I think it's actually better to model this after Mr. Fixer's Hoist Chain, just adding a check that the dealt damage is lightning before alongside the check that it actually did damage. Less chance of having bad interaction with damage-type changing effects.

**Comment by cdallasanta** [comment]
Very good call. I'll look into that next.

**Comment by cdallasanta** [comment]
The git diff looks pretty nasty, but it's essentially replacing it all with what Hoist Chain has, with a slightly larger criteria on the initial trigger for Fall's cirteria.

File: CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/FallCardController.cs [hunk 2]
```diff
@@ -14,31 +14,27 @@ public override void AddTriggers()
 		{
 			//Whenever LadyOfTheWood deals lightning damage to a target, reduce damage dealt by that target by 1 until the start of your next turn.
 			Func<DealDamageAction,bool> criteria = (DealDamageAction dd) => dd.DamageSource != null && dd.DamageSource.IsSameCard(base.CharacterCard) && dd.DamageType == DamageType.Lightning;
```
Comment (LNBertolini) [inline CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/FallCardController.cs:16]: The damage-type criteria should not be in this location, because the AddStatusEffectToDamage triggertype is really early in the trigger resolution order, and this will likely cause misapplications or missed applications if there's a damage-type changing effect. If you want to see for yourself, you could try tests with Megalopolis's Cramped Quarters Combat and/or Visionary's Twist the Ether

File: CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/FallCardController.cs [hunk 3]
```diff
@@ -14,31 +14,27 @@ public override void AddTriggers()
...
-				ReduceDamageStatusEffect reduceDamageStatusEffect = new ReduceDamageStatusEffect(1);
-				reduceDamageStatusEffect.SourceCriteria.IsSpecificCard = dd.Target;
-				reduceDamageStatusEffect.UntilStartOfNextTurn(base.TurnTaker);
-				IEnumerator coroutine = base.AddStatusEffect(reduceDamageStatusEffect);
-				if (base.UseUnityCoroutines)
-				{
-					yield return base.GameController.StartCoroutine(coroutine);
-				}
-				else
+				if (dd2.DidDealDamage)
```
Comment (LNBertolini) [inline CauldronMods/Controller/Heroes/LadyOfTheWood/Cards/FallCardController.cs:24]: Check that the damage type is Lightning here, instead of in the initial trigger criteria.

**Comment by cdallasanta** [comment]
I added a test using Imbued Fire (which failed as you'd expect). Moved the type check and all tests pass now.

**Comment by cdallasanta** [comment]
Thanks for the catch.

**Review by LNBertolini — APPROVED** [review]
