### PR TITLE
Hidden Detour custom string

### LINKED ISSUE #1007: Enhancement Request: Which Hidden Detour to activate first?
**Describe the bug**
When 2 or more copies of Gyrosaur's Hidden Detour are in play, and an environment card is about to enter play, the user is not prompted as to which Hidden Detour should activate first. The user has to Meanwhile... back to their play area and check the Hidden Detours to see which they want to use, if at all. 

**What does it affect**
Card(s): Hidden Detour
Deck(s): Gyrosaur

**Expected behavior**
"Which of these cards (shows both Hidden Detours) should activate first?"

### PR DESCRIPTION
**Pull request by cdallasanta**
Closes #1007

Hidden Detour now prompts: "Do you want to put {cardENteringPlay} under Hidden Detour and put {cardUnderneath} into play?", and if there are multiple Hidden Detours, shows the player what other cards can be swapped out.

### CODE REVIEW

File: CauldronMods/Controller/Heroes/Gyrosaur/Cards/HiddenDetourCardController.cs [hunk 1]
```diff
@@ -338,5 +338,15 @@ private bool IsCardUnder(Card card)
         {
             return Card.UnderLocation.HasCard(card); // AllDetourUnderCards.Contains(card);
         }
+
+        public override CustomDecisionText GetCustomDecisionText(IDecision decision)
+        {
+            return new CustomDecisionText(
+                $"Do you want to put this card beneath Hidden Detour and put {this.Card.UnderLocation.TopCard.Title} into play?",
```
Comment (cdallasanta) [inline CauldronMods/Controller/Heroes/Gyrosaur/Cards/HiddenDetourCardController.cs:345]: I was trying to figure out how to reference the card about to enter play instead of "this card," but couldn't figure it out the with variables available to me. This is likely fine (especially for long Env card names, though inconsistent with the current text: "Do you want to put {card entering play} under Hidden Detour?"

Comment (LNBertolini) [reply CauldronMods/Controller/Heroes/Gyrosaur/Cards/HiddenDetourCardController.cs:345]: Perhaps try
`
var cardName = "this card"
if(decision is YesNoCardDecision yncd)
{
    cardName = yncd.Card.Title;
}`

Comment (cdallasanta) [reply CauldronMods/Controller/Heroes/Gyrosaur/Cards/HiddenDetourCardController.cs:345]: Fantastic. Added.

**Comment by cdallasanta** [comment]
Another option might be to use ExtraInfo like in #1352, or AkashThriya's "Rapid Growth". Instead of "Cards discarded so far:" it could say "Cards under other Hidden Detours:". That more closely resolves the original ticket. I'll give that a whirl before we merge this.

**Comment by cdallasanta** [comment]
I added in the ExtraInfo feature. Now, if there are multiple Hidden Detours in play, the decision looks like:
image

And with only one Hidden Detour in play:
image

File: CauldronMods/Controller/Heroes/Gyrosaur/Cards/HiddenDetourCardController.cs [hunk 2]
```diff
@@ -129,8 +129,30 @@ private IEnumerator AskToSwapCard(GameAction ga)
...
             }
 
-            var storedYesNo = new List<YesNoCardDecision>();
-            IEnumerator coroutine = GameController.MakeYesNoCardDecision(DecisionMaker, SelectionType.MoveCardToUnderCard, cardEnteringPlay, storedResults: storedYesNo, cardSource: GetCardSource());
+            Func<string> extraInfo;
+            List<Card> otherDetourCards = TurnTaker.GetCardsWhere((card) => card.Identifier == "HiddenDetour" && card.IsInPlayAndHasGameText && card != this.Card).ToList();
+            if (otherDetourCards.Count > 0)
+            {
+                string cardsUnder = "";
+                foreach (Card detour in otherDetourCards)
```
Comment (cdallasanta) [inline CauldronMods/Controller/Heroes/Gyrosaur/Cards/HiddenDetourCardController.cs:137]: Is it possible to have more than two Hidden Detours in play (or cards with the identifier "HiddenDetour")? There are only two in Gyro's deck, and anything that copies equipments probably doesn't have it's identifier changed. If there would only ever be two, I can simplify this block a bit. If there could be more than two, this block should catch it.

File: CauldronMods/Controller/Heroes/Gyrosaur/Cards/HiddenDetourCardController.cs [hunk 3]
```diff
@@ -129,8 +129,30 @@ private IEnumerator AskToSwapCard(GameAction ga)
...
+                {
+                    if (detour.UnderLocation.Cards.Count() > 0)
+                    {
+                        cardsUnder += $"{detour.UnderLocation.Cards.First().Title}, ";
+                    }
+                }
+
+                extraInfo = () => $"Cards underneath other Hidden Detours: {cardsUnder.Remove(cardsUnder.Length - 2, 2)}";
```
Comment (cdallasanta) [inline CauldronMods/Controller/Heroes/Gyrosaur/Cards/HiddenDetourCardController.cs:145]: I'm not in love with this wording, but can't come up with something better.

**Review by LNBertolini — APPROVED** [review]
