### PR TITLE
Blackwood Forest - issue fixes #234, #235

### LINKED ISSUE #234: Blackwood Forest - Overgrown Cathedral UI
**Describe the bug**
Not a bug, just a UI improvement - the Cathedral, when given the option to destroy it at the start of the environment turn, says "Do you want to discard Overgrown Cathedral?" 

**What does it affect**
Card(s): Overgrown Cathedral
Deck(s): Blackwood Forest

**To Reproduce**
Have Overgrown Cathedral in play and let it start an environment turn. 

**Expected behavior**
The UI to suggest "Do you want to destroy Overgrown Cathedral?" 

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by breenyoung**
* Fix for #234  
* Fix for #235
* Change to special string in Dense Brambles from suggestion from @Vilnor

### CODE REVIEW

**Comment by LNBertolini** [comment]
Desolation would be more easily fixed by changing the SelectionType to PreventDamage and swapping the yes/no responses, I think. Also more technically correct (you get the option to either discard all the cards or none of them, you don't get to take half-measures).

File: Controller/Environments/BlackwoodForest/Cards/DesolationCardController.cs [hunk 1]
```diff
@@ -37,70 +34,31 @@ public override void AddTriggers()
...
+                        new LinqCardCriteria(card => card.Location == httc.HeroTurnTaker.Hand, "hand"),
+                        new[] { new MoveCardDestination(httc.TurnTaker.Trash) }, cardSource: base.GetCardSource())),
 
-        private IEnumerator ChoiceResponse(TurnTakerController ttc)
-        {
-            List<YesNoCardDecision> yesNoResults = new List<YesNoCardDecision>();
-            IEnumerator yesNoRoutine = base.GameController.MakeYesNoCardDecision(ttc.ToHero(),
-                SelectionType.DiscardCard, base.Card, storedResults: yesNoResults, cardSource: base.GetCardSource());
+                new Function(httc, $"Take {damageToDeal} psychic damage", SelectionType.DealDamage,
+                    () => this.DealDamage(this.Card, httc.CharacterCard, damageToDeal, DamageType.Psychic, cardSource: base.GetCardSource()))
```
Comment (LNBertolini) [inline Controller/Environments/BlackwoodForest/Cards/DesolationCardController.cs:48]:
```suggestion
                    () => this.DealDamage(this.Card, (Card c) => httc.CharacterCards.Contains(c) && c.IsTarget, damageToDeal, DamageType.Psychic, cardSource: base.GetCardSource()))
```

Keep this bit from breaking on the Sentinels

**Review by LNBertolini — APPROVED** [review]
