### PR TITLE
Cypher UI decision improvements

### LINKED ISSUE #1214: Cypher Moving Augments UI (e.g. Cyborg Blaster)
**Describe the bug**
Many of Cypher's cards (e.g. Cyborg Blaster) let him move around his augments.  The selecting an augment prompt is currently the same as the selecting the character target - it would make more sense to have it read "Cypher, select a card to move" (rather than select a card to move next to)

Edit:  Maybe be even more specific if it's going to be custom anyways - have prompts like

"Cypher, select an augment to move"
and
"Cypher, select a hero to move (the augment) next to"

For extra fanciness

**What does it affect**
Card(s): Cyborg Blaster (and probably also Cyborg Punch, Neural Interface, Backup Plan)
Deck(s): Cypher

**Screenshots**
image

### PR DESCRIPTION
**Pull request by wrhyme29**
Closes #1214

### CODE REVIEW

File: CauldronMods/Controller/Heroes/Cypher/Cards/NeuralInterfaceCardController.cs [hunk 1]
```diff
@@ -22,9 +22,11 @@ public NeuralInterfaceCardController(Card card, TurnTakerController turnTakerCon
             ShowSpecialStringAugmentsInPlay();
         }
 
+        private int customTextPowerNumeral = 1;
         public override IEnumerator UsePower(int index = 0)
         {
             int augsToMove = GetPowerNumeral(0, 1);
+            customTextPowerNumeral = augsToMove;
             // You may move 1 Augment in play next to a new hero.
             var scd = new SelectCardsDecision(GameController, DecisionMaker, (Card c) => IsInPlayAugment(c), SelectionType.MoveCardNextToCard,
```
Comment (cdallasanta) [inline CauldronMods/Controller/Heroes/Cypher/Cards/NeuralInterfaceCardController.cs:31]: Does this need SelectionType.Custom?

Comment (wrhyme29) [reply CauldronMods/Controller/Heroes/Cypher/Cards/NeuralInterfaceCardController.cs:31]: Yes it does. Good catch

**Review by cdallasanta — APPROVED** [review]
