### PR TITLE
Uh, Yeah, I'm That Guy! and Abracadabra! interaction fix

### LINKED ISSUE #1674: Uh, Yeah, I'm That Guy! always destroys Abracadabra!
**Describe the bug**
When Abracadabra! and Uh, Yeah, I'm That Guy! copying Abracadabra are both in play, they will both prompt to save any other hero cards that get destroyed. When we choose Uh, Yeah, I'm That Guy! to move the card being destroyed to hand, Abracadabra! is destroyed instead of it.

**What does it affect**
Card(s): Uh, Yeah, I'm That Guy!, Abracadabra!
Deck(s): Guise, Magnificent Mara

**To Reproduce**
1. Have Mara play Abracadabra!
2. Have Guise play Uh, Yeah, I'm That Guy! copying Mara
3. Have a third hero card be played and destroyed, and select "Yes" when prompted by **Guise** to move the card to hand anyway
4. Abracadabra! gets destroyed anyway

**Expected behavior**
Uh, Yeah, I'm That Guy! should be destroyed. Abracadabra! should remain in play.

**Screenshots**

**Additional context**
Root cause of issue seems to be incorrect `this` binding on `AfterDestroyedAction` callback - fix uses `Journal` to get around this
abrayeah

### PR DESCRIPTION
**Pull request by ever-3W**
Closes #1674

### CODE REVIEW

**Review by jamespicone — CHANGES_REQUESTED** [review]
I like this a lot better than your other workaround, thanks! Just a couple minor code style fixes requested, then if this passes all the tests i think we're good to merge.

File: CauldronMods/Controller/Heroes/MagnificentMara/Cards/AbracadabraCardController.cs [hunk 1]
```diff
@@ -48,6 +49,7 @@ private IEnumerator MayReturnDestroyedResponse(DestroyCardAction dc)
 
             if (DidPlayerAnswerYes(decisionResult))
             {
+                Journal.RecordCardProperties(Card, SavedCard, dc.CardToDestroy.Card);
                 dc.SetPostDestroyDestination(dc.CardToDestroy.Card.Owner.ToHero().Hand);
                 dc.AddAfterDestroyedAction(() => DestroyThisCardIfMovedResponse(dc), this);
```
Comment (jamespicone) [inline CauldronMods/Controller/Heroes/MagnificentMara/Cards/AbracadabraCardController.cs:54]: Just had a thought: Does `dc.AddAfterDestroyedAction(() => DestroyThisCardIfMovedResponse(dc, this), this)` and modifying DestroyThisCardIfMovedResponse to take a cardcontroller to destroy work?

Comment (ever-3W) [reply CauldronMods/Controller/Heroes/MagnificentMara/Cards/AbracadabraCardController.cs:54]: I have tried that, both as an instance method and an extension method of `CardController`. Neither worked.

Comment (jamespicone) [reply CauldronMods/Controller/Heroes/MagnificentMara/Cards/AbracadabraCardController.cs:54]: Just did some fiddling; `dc.AddAfterDestroyedAction(() => DestroyThisCardIfMovedResponse(dc, Card), this);` and `private IEnumerator DestroyThisCardIfMovedResponse(DestroyCardAction dc, Card savingCard)` passes the tests. Passing `this` was a silly idea and won't work because it's just the CardController, but the `CardController.Card` property does the appropriate replacement magic. Good plan on solving the problem and thank you for working out what's going wrong. :)

**Review by jamespicone — APPROVED** [review]
