### PR TITLE
Swarming frequency Special String

### LINKED ISSUE #1347: Swarming Frequency (cricket) Special String for Environment target if any
**Describe the bug**
No special string currently for swarming frequency.

**What does it affect**
Card(s):  Swarming Frequency
Deck(s): Cricket

**Expected behavior**
Indicate the current environment target with the lowest HP, or that there is no environment targets in play.

**Screenshots**
From Handelabra Live #317
https://www.youtube.com/watch?v=floT3Db5P1I&t=3067s

### PR DESCRIPTION
**Pull request by wrhyme29**
Closes #1347

### CODE REVIEW

File: CauldronMods/Controller/Heroes/Cricket/Cards/SwarmingFrequencyCardController.cs [hunk 1]
```diff
@@ -12,6 +12,7 @@ public class SwarmingFrequencyCardController : CardController
         public SwarmingFrequencyCardController(Card card, TurnTakerController turnTakerController) : base(card, turnTakerController)
         {
             AllowFastCoroutinesDuringPretend = false;
+            SpecialStringMaker.ShowNumberOfCardsInPlay(new LinqCardCriteria(c => c.IsEnvironmentTarget, "", useCardsSuffix: false, singular: "environment target", plural: "environment targets"));
```
Comment (cdallasanta) [inline CauldronMods/Controller/Heroes/Cricket/Cards/SwarmingFrequencyCardController.cs:15]: Would we instead want to display the environment target with the lowest hp, if one exists?

Comment (wrhyme29) [reply CauldronMods/Controller/Heroes/Cricket/Cards/SwarmingFrequencyCardController.cs:15]: Yeah that works well. I would do this with two special strings [these might be slightly incorrect names and stuff, as this is from memory] :

1) SpecialStringMaker.ShowEnvironmentTargetWithLowestHP().Condition = () => FindCardsWhere(c => c.IsEnvironmentTarget).Count()> 0

2)SpecialStringMaker.ShowSpecialString(() => "There are no environment targets in play").Condition = () => FindCardsWhere(c => c.IsEnvironmentTarget).Count() == 0

**Review by LNBertolini — APPROVED** [review]
